spring.application.name=job-
spring.datasource.url=jdbc:mysql://localhost:3306/job_portal
spring.datasource.username=root
spring.datasource.password=7000@she

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
